### ISSUE TITLE
Modificacion de vista de partidos

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/copa_sudamericana_cliente#14]
Se debe modificar la vista de partidos en el cliente para que muestre los partidos en fechas de la forma especificada en los requerimientos despues de que se realice la (distribucion de partidos)[]

**Comment by CarlosGutierrezArdila** [comment]
![image](https://user-images.githubusercontent.com/32855979/57735550-92062d00-766a-11e9-988d-1a2600af0daf.png)
Se debe generar una vista en el componente similar a la de la imagen

**Comment by macaguegi** [comment]
Este issue está duplicado y está disponible en : https://github.com/udistrital/copa_sudamericana_cliente/issues/11
